name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t devops-homelab:latest ./app

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            git pull https://github.com/gavin-alan/devops-homelab.git main
            cp devops-homelab/app/app.py .
            cp devops-homelab/app/requirements.txt .
            cp devops-homelab/app/Dockerfile .
            rm -rf devops-homelab
            docker stop homelab-app || true
            docker rm homelab-app || true
            docker rmi devops-homelab:latest || true
            docker build -t devops-homelab:latest .
            docker run -d -p 80:5000 --name homelab-app devops-homelab:latest
